language: c
dist: trusty
sudo: false

# Based on https://github.com/greghendershott/travis-racket


env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.10.1


before_install:
- git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
- cat ~/travis-racket/install-racket.sh | bash   # pipe to bash not sh!
- export PATH="${RACKET_DIR}/bin:${PATH}"   # install-racket.sh can't set for us
- raco pkg install --no-setup rosette   # install rosette without compiling its docs
- raco setup -Dl rosette


install:
 - raco pkg install --deps search-auto


script:
 - raco test -x -p colocolo

